"""First-run bootstrap: installs steamcmd, downloads CS2, installs plugins,
and writes a default launch script -- whichever of those are missing. Lets
the bot go from a bare VM to a running server on the very first
`python -m cs2bot.bot` without any manual steamcmd/CS2 setup; only the
Discord/RCON side of config.json needs to be filled in by hand.

Every check here is idempotent (a few stat calls) and every action is a
no-op once its target exists, so calling ensure_installed() on every startup
-- not just the first -- costs nothing on an already-set-up box.
"""

import logging
import stat
import shutil
import tarfile
import urllib.request
from pathlib import Path

from . import plugins, updater

log = logging.getLogger("cs2bot.bootstrap")

STEAMCMD_LINUX_URL = "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"

_DEFAULT_LAUNCH_SCRIPT = """#!/bin/bash
# Auto-generated by cs2bot on first run because {launch_script} didn't exist
# yet -- the bot never overwrites this file once it's there, so tune launch
# options (GSLT token, hostname, workshop maps, ...) freely.
exec {cs2_bin} -dedicated +map {default_map} +game_type 0 +game_mode 0 \\
    -usercon +rcon_password {rcon_password} +hostname "CS2 Dedicated Server" \\
    -port {port}
"""


def steamcmd_path(cfg) -> str | None:
    """Absolute path to a usable steamcmd executable, or None if neither
    the configured name/path nor a previously bootstrapped copy exists."""
    found = shutil.which(cfg.steamcmd)
    if found:
        return found
    local = cfg.steamcmd_install_dir / "steamcmd.sh"
    return str(local) if local.is_file() else None


def install_steamcmd(cfg) -> str:
    """Download and extract steamcmd's Linux release into
    cfg.steamcmd_install_dir. Returns the path to steamcmd.sh."""
    dest = cfg.steamcmd_install_dir
    dest.mkdir(parents=True, exist_ok=True)
    log.info("downloading steamcmd to %s", dest)
    with urllib.request.urlopen(STEAMCMD_LINUX_URL, timeout=120) as resp:
        with tarfile.open(fileobj=resp, mode="r|gz") as tf:
            plugins.extract_tar(tf, dest)
    script = dest / "steamcmd.sh"
    script.chmod(script.stat().st_mode | stat.S_IEXEC)
    log.info("steamcmd installed at %s", script)
    return str(script)


def cs2_installed(cfg) -> bool:
    """True if a CS2 dedicated server binary is already present."""
    return (cfg.csgo_dir.parent / "bin" / "linuxsteamrt64" / "cs2").is_file()


def install_cs2(cfg) -> None:
    """Blocking: anonymous-login steamcmd install of the CS2 dedicated
    server (app 730) into cfg.steam_library. Reuses updater's own
    steamcmd runner so a fresh install gets the same retry/disk-full
    handling as a routine update, and relays steamcmd's output live since
    this is a large (several GB) download."""
    cfg.steam_library.mkdir(parents=True, exist_ok=True)
    log.info(
        "no CS2 install found; installing app %s into %s -- this downloads "
        "several GB and may take a while",
        cfg.app_id, cfg.steam_library,
    )
    ok, reason, debug = updater._run_steamcmd_blocking(cfg)
    if not ok:
        raise RuntimeError(f"CS2 install failed: {reason}\n{debug}")


def plugins_installed(cfg) -> bool:
    return (cfg.csgo_dir / "addons" / "metamod").is_dir()


def ensure_launch_script(cfg) -> None:
    """Write a bare-bones default launch script if the configured one
    doesn't exist yet. Never overwrites an existing script -- once you've
    tuned your own launch options, the bot leaves it alone."""
    script = Path(cfg.launch_script)
    if script.is_file():
        return
    cs2_bin = cfg.csgo_dir.parent / "bin" / "linuxsteamrt64" / "cs2"
    script.parent.mkdir(parents=True, exist_ok=True)
    # The rcon password is templated into this file, so it must be owner-only
    # from the moment it exists -- create it closed rather than letting
    # write_text's default (world-readable) apply first.
    script.touch(mode=0o600)
    script.write_text(
        _DEFAULT_LAUNCH_SCRIPT.format(
            launch_script=script,
            cs2_bin=cs2_bin,
            default_map=cfg.default_map,
            rcon_password=cfg.rcon_password or "changeme",
            port=cfg.join_port,
        ),
        encoding="utf-8",
    )
    script.chmod(0o700)
    log.warning(
        "wrote a bare-bones launch script at %s -- review it (GSLT token, "
        "hostname, workshop maps, etc.) before relying on it long-term",
        script,
    )


def ensure_installed(cfg) -> None:
    """Bring a bare VM up to a runnable state: steamcmd, CS2 itself, the
    three plugins, and a launch script, installing whichever are missing."""
    steamcmd = steamcmd_path(cfg)
    if not steamcmd:
        log.info("steamcmd not found on PATH or at %s; installing it", cfg.steamcmd_install_dir)
        steamcmd = install_steamcmd(cfg)
    cfg.steamcmd = steamcmd

    cfg.install_dir.mkdir(parents=True, exist_ok=True)

    fresh_install = not cs2_installed(cfg)
    if fresh_install:
        install_cs2(cfg)

    if fresh_install or not plugins_installed(cfg):
        log.info("installing Metamod/CounterStrikeSharp/MatchZy")
        for name in plugins.PLUGINS:
            plugins.install(name, cfg.csgo_dir)
        plugins.patch_gameinfo(cfg.csgo_dir)

    ensure_launch_script(cfg)
